project/Comunidad/urls.py
from django.urls import path
from . import views

app_name = "Comunidad"

urlpatterns = [
    path('', views.home, name="home"),
    path('registrarusuario/', views.RegistrarUsuario.as_view(), name='registrar_usuario'),
    ]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("comunidad/", include("Comunidad.urls")),
    path("servicios/", include("servicios.urls")), 
]

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path('about/', views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/servicios/urls.py
from django.urls import path
from . import views

app_name = "servicios"

urlpatterns = [
    path('', views.home, name="home"),
    path('crearservicio/', views.ServicioCrear.as_view(), name="servicios_crear"),
    path('detalleservicio/<int:pk>', views.servicios_detalle, name="servicios_detalle"),
    path('actualizarservicio/<int:pk>', views.ServicioActualizar.as_view(), name="servicios_actualizar"),
    path('borrarservicio/<int:pk>', views.ServicioBorrar.as_view(), name="servicios_borrar")
    ]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widget = {
            'username': forms.TextInput(attrs={"class": "form-control"}),
            'password': forms.PasswordInput(attrs={"class": "form-control"}),
        }
        
class CustomUserCreationForm(UserCreationForm):
    class Meta: 
        model = User
        fields = ["username", "password1", "password2"]
        widget = {
            'username': forms.TextInput(attrs={"class": "form-control"}),
            'password1': forms.PasswordInput(attrs={"class": "form-control"}), 
            'password2': forms.PasswordInput(attrs={"class": "form-control"}), 
        }

project/core/views.py
from django.contrib.auth.views import LoginView
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .forms import CustomAuthenticationForm, CustomUserCreationForm

def home(request):
    return render(request, "core/index.html")

def about(request):
    return render(request, 'core/about.html')

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "core/index.html", {"mensaje": "Usuario creado"})
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/core/templates/core/componentes/footer.html
<footer class="py-2 bg-dark fixed-bottom ">
    <div class="container px-4">
        <p class="m-0 text-center text-white">Coderhouse: Comisión 54135</p>
    </div>
</footer>

project/core/templates/core/componentes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"
     id="mainNav"
     mb-2>
    <div class="container px-4">
        <a class="navbar-brand" href="#!">🦸‍♀️Mujeres Únicas e Irrepetibles🦸‍♀️</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:home' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:about' %}">Somos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'servicios:home' %}">Servicios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Comunidad:home' %}">Comunidad</a>
                </li>
                <li class="nav-item">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:register' %}">Nuevo Staff</a>
                </li>
                <form action="{% url 'core:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark"> Cerrar Sesión </button>
                </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-bg-info">{{ user.username }}</a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:login' %}">Iniciar Sesión</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>