project/Comunidad/urls.py
from django.urls import path
from . import views

app_name = "Comunidad"

urlpatterns = [
    path('', views.home, name="home"),
    path('registrarusuario/', views.RegistrarUsuario.as_view(), name='registrar_usuario'),
    ]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("comunidad/", include("Comunidad.urls")),
    path("servicios/", include("servicios.urls")), 
]

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path('about/', views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/Comunidad/models.py
from django.db import models

class Psicologa(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField(null=True, verbose_name="fecha de nacimiento")
    telefono = models.PositiveIntegerField(unique=True)
    correo = models.CharField(max_length=200)
    usuario = models.CharField(max_length=200, unique=True)
    contraseña = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return f"🌸Psicologa {self.nombre} - 👥{self.usuario} - 📱{self.telefono} - 📧{self.correo}" 

class Equipo(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField(null=True, verbose_name="fecha de nacimiento")
    telefono = models.PositiveIntegerField(unique=True)
    correo = models.CharField(max_length=200)
    area = models.CharField(max_length=200, verbose_name="Área de Trabajo")
    usuario = models.CharField(max_length=200, unique=True)
    contraseña = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return f"{self.nombre} - area: {self.area} 😎  - 👥{self.usuario} - 📱{self.telefono} - 📧{self.correo}"
    
    class Meta: 
        verbose_name_plural = "Equipo de Trabajo"
    
class Usuario(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_nacimiento = models.DateField(null=True, verbose_name="fecha de nacimiento")
    telefono = models.IntegerField(unique=True)
    correo = models.CharField(max_length=200)
    usuario = models.CharField(max_length=200, unique=True)
    
    def __str__(self) -> str:
        return f"🙋‍♀️ {self.usuario} 🟣 {self.nombre} - 📱{self.telefono} - 📧{self.correo}"

class Comunidad(models.Model):
    nombre = models.CharField(max_length=200)
    psicologa = models.ForeignKey(Psicologa, on_delete=models.SET_NULL, null=True, blank=True, related_name='psicologas')
    usuario = models.ManyToManyField(Usuario)
    
    def __str__(self) -> str:
        return self.nombre
    
    class Meta: 
        verbose_name_plural = "Comunidad"

project/Comunidad/forms.py
from django import forms
from . import models

class RegistrarUsuarioForm(forms.ModelForm):
    class Meta:
        model = models.Usuario 
        fields = '__all__'

project/Comunidad/views.py
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . import forms, models

def home(request):
    psicologas = models.Psicologa.objects.all()
    equipo = models.Equipo.objects.all()
    usuarios = models.Usuario.objects.all()
    context = {
        "psicologas": psicologas,
        "equipo": equipo, 
        "usuarios": usuarios
    }
    return render(request, "Comunidad/index.html", context)

class RegistrarUsuario(CreateView):
    model = models.Usuario
    template_name = "comunidad/registrarusuario.html"
    form_class = forms.RegistrarUsuarioForm
    success_url = reverse_lazy("Comunidad:home")

project/Comunidad/templates/Comunidad/index.html
{% extends 'core/base.html' %}

{% block contenido %}
    <div class="container">
        <div class="row justify-content-center py-5">
            <div class="col-md-8">
                <div class="card shadow p-4 rounded text-center">
                    <h2 class="card-title mb-4" style="color: #1a1a1a;">"¡Únete a nuestra comunidad y comienza tu viaje hacia tu mejor versión!"</h2>
                    <div class="custom-text lead mb-4" style="color: #495057;">
                        <p>"Cada pequeño paso te acerca más a la</p>
                        <p> mujer extraordinaria que estás destinada a ser."</p>
                        <p>¡No esperes más para empezar!</p>
                    </div>
                    <a href="{% url 'Comunidad:registrar_usuario' %}" class="btn btn-primary btn-lg"> 👉 Únete aquí 👈</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow p-4 rounded">
                <h2 class="card-title mb-4 text-center" style="color: #1a1a1a;">Nuestro Equipo de Trabajo</h2>
                <ul class="list-group text-left">
                    {% for psicologa in psicologas %}
                    <li class="list-group-item" style="text-align: justify;">🌸 {{ psicologa.nombre }} - Psicóloga 🧙‍♀️</li>
                    {% endfor %}
                    {% for miembro in equipo %}
                    <li class="list-group-item" style="text-align: justify;">👨‍💻 {{ miembro.nombre }} - {{ miembro.area }} 😎</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card shadow p-4 rounded">
                <h2 class="card-title mb-4 text-center" style="color: #1a1a1a;">Usuarias Registradas</h2>
                <div class="row">
                    {% for usuario in usuarios %}
                    <div class="col-md-4 mb-3">
                        <div class="list-group-item" style="text-align: left; color: #1a1a1a;">🦸‍♀️ {{ usuario.usuario }}</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div>
            <button style="margin-top: 40px; background-color: #f0e6d2; border: none; padding: 10px 20px; border-radius: 5px;">
                <a href="{% url 'core:home' %}" style="text-decoration: none; color: black;">Volver a Home</a>
            </button>
          </div>  
</div>
{% endblock contenido %}

project/Comunidad/templates/Comunidad/registrarusuario.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
<h2 class="card-title text-center mb-4" style="color: #1a1a1a;">🤗 Bienvenida a nuestra Comunidad 🤗</h2>
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card p-4 shadow-sm rounded" style="background-color: #faf3e0;">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_nombre" class="form-label" style="color: #000;">Nombre</label>
                        <input type="text" class="form-control form-control-lg" id="id_nombre" name="nombre" style="background-color: #faf3e0; color: #000;">
                    </div>
                    <div class="mb-3">
                        <label for="id_fecha_nacimiento" class="form-label" style="color: #000;">Fecha de nacimiento</label>
                        <input type="date" class="form-control form-control-lg" id="id_fecha_nacimiento" name="fecha_nacimiento" style="background-color: #faf3e0; color: #000;">
                    </div>
                    <div class="mb-3">
                        <label for="id_telefono" class="form-label" style="color: #000;">Teléfono</label>
                        <input type="tel" class="form-control form-control-lg" id="id_telefono" name="telefono" style="background-color: #faf3e0; color: #000;">
                    </div>
                    <div class="mb-3">
                        <label for="id_correo" class="form-label" style="color: #000;">Correo</label>
                        <input type="email" class="form-control form-control-lg" id="id_correo" name="correo" style="background-color: #faf3e0; color: #000;">
                    </div>
                    <div class="mb-3">
                        <label for="id_usuario" class="form-label" style="color: #000;">Usuario</label>
                        <input type="text" class="form-control form-control-lg" id="id_usuario" name="usuario" style="background-color: #faf3e0; color: #000;">
                    </div>
                    <button type="submit" class="btn btn-success btn-lg">Enviar</button>
                </form>
            </div>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center">
            <img src="{% static 'core/img/registrarusuario1.webp' %}" class="img-fluid rounded" alt="Imagen derecha">
        </div>
    </div>
</div>
<div class="mt-4 text-center">
    <button class="btn btn-light">
        <a href="{% url 'Comunidad:home' %}" style="text-decoration: none; color: black;">Volver a Registrarse</a>
    </button>
</div>
{% endblock contenido %}