project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("comunidad/", include("Comunidad.urls")),
    path("servicios/", include("servicios.urls")), 
]

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path('about/', views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/servicios/urls.py
from django.urls import path
from . import views

app_name = "servicios"

urlpatterns = [
    path('', views.home, name="home"),
    path('crearservicio/', views.ServicioCrear.as_view(), name="servicios_crear"),
    path('detalleservicio/<int:pk>', views.servicios_detalle, name="servicios_detalle"),
    path('actualizarservicio/<int:pk>', views.ServicioActualizar.as_view(), name="servicios_actualizar"),
    path('borrarservicio/<int:pk>', views.ServicioBorrar.as_view(), name="servicios_borrar")
    ]

project/servicios/models.py
from django.db import models

class Servicios(models.Model):
    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=500, verbose_name="descripción")
    valor = models.IntegerField(verbose_name="valor (CLP)")
    cantidad = models.IntegerField(null=True, blank=True)
        
    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        verbose_name = "Nuestros Servicios"
        verbose_name_plural = "Nuestros Servicios"

project/servicios/forms.py
from django import forms
from . import models

class CrearServicioForm(forms.ModelForm):
    class Meta:
        model = models.Servicios
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'style': 'background-color: #faf3e0; color: #000;',
                'maxlength': '200',
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'form-control',
                'style': 'background-color: #faf3e0; color: #000;',
                'rows': 10,
                'maxlength': '500',
            }),
            'valor': forms.NumberInput(attrs={
                'class': 'form-control',
                'style': 'background-color: #faf3e0; color: #000;',
            }),
            'cantidad': forms.NumberInput(attrs={
                'class': 'form-control',
                'style': 'background-color: #faf3e0; color: #000;',
            }),
        }

project/servicios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models, forms

def home(request):
    consulta_servicios = models.Servicios.objects.all()
    context = {"servicios": consulta_servicios}
    return render(request, "servicios/index.html", context)

def servicios_detalle(request, pk: int):
    query = models.Servicios.objects.get(id=pk)
    return render(request, "servicios/detalleservicio.html", {"servicio": query})

class ServicioCrear(LoginRequiredMixin, CreateView):
    model = models.Servicios
    template_name = "servicios/crearservicio.html"
    form_class = forms.CrearServicioForm
    success_url = reverse_lazy("servicios:home")
    
class ServicioActualizar(LoginRequiredMixin, UpdateView):
    model = models.Servicios
    template_name = "servicios/actualizarservicio.html"
    form_class = forms.CrearServicioForm
    success_url = reverse_lazy("servicios:home")

class ServicioBorrar(LoginRequiredMixin, DeleteView):
    model = models.Servicios
    template_name = "servicios/borrarservicio.html"
    success_url = reverse_lazy("servicios:home")

project/servicios/templates/servicios/actualizarservicio.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    <h1 style="color: #1a1a1a;">👩‍💻 Actualización de Servicio 👩‍💻</h1>
{% endblock titulo %}

{% block contenido %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 d-flex align-items-center justify-content-center">
                <img src="{% static 'core/img/serviciocrear1.webp' %}" class="img-fluid rounded" alt="Descripción de la imagen">
            </div>
            <div class="col-md-6">
                <div class="card p-4 shadow-sm rounded">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.nombre.id_for_label }}" class="form-label" style="color: #000;">Nombre</label>
                            {{ form.nombre }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.descripcion.id_for_label }}" class="form-label" style="color: #000;">Descripción</label>
                            {{ form.descripcion }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.valor.id_for_label }}" class="form-label" style="color: #000;">Valor (CLP)</label>
                            {{ form.valor }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.cantidad.id_for_label }}" class="form-label" style="color: #000;">Cantidad</label>
                            {{ form.cantidad }}
                        </div>
                        <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div>
        <button style="margin-top: 20px; background-color: #f0e6d2; border: none; padding: 10px 20px; border-radius: 5px;">
            <a href="{% url 'servicios:home' %}" style="text-decoration: none; color: black;">Volver a Servicios</a>
        </button>
    </div>
{% endblock contenido %}

project/servicios/templates/servicios/borrarservicio.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    <h1 style="color: #1a1a1a; margin-bottom: 20px;">🤯 Dar de baja un Servicio 🤯</h1>
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card p-4 shadow-sm rounded" style="background-color: #faf3e0;">
                <p class="fs-5 text-dark" style="margin-bottom: 20px;">¿Quieres dar de baja el servicio <br>"{{ servicios.nombre }}"?<br></p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Confirmar</button>
                </form>
            </div>
            <div class="mt-4 text-center">
                <button style="background-color: #f0e6d2; border: none; padding: 10px 20px; border-radius: 5px;">
                    <a href="{% url 'servicios:home' %}" style="text-decoration: none; color: black;">Volver a Servicios</a>
                </button>
            </div>
        </div>
        <div class="col-md-4 d-flex align-items-center justify-content-center">
            <img src="{% static 'core/img/borrarservicio.webp' %}" class="img-fluid" alt="Imagen de ejemplo">
        </div>
    </div>
</div>
{% endblock contenido %}

project/servicios/templates/servicios/crearservicio.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    <h1 style="color: #1a1a1a;">🥰 Crea un nuevo servicio para la Comunidad 🥰</h1>
{% endblock titulo %}

{% block contenido %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 d-flex align-items-center justify-content-center">
                <img src="{% static 'core/img/serviciocrear1.webp'%}" class="img-fluid rounded" alt="Descripción de la imagen">
            </div>
            <div class="col-md-6">
                <div class="card p-4 shadow-sm rounded">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_nombre" class="form-label" style="color: #000;">Nombre</label>
                            <input type="text" class="form-control" id="id_nombre" name="nombre" style="background-color: #faf3e0; color: #000;" maxlength="200">
                        </div>
                        <div class="mb-3">
                            <label for="id_descripcion" class="form-label" style="color: #000;">Descripción</label>
                            <textarea class="form-control" id="id_descripcion" name="descripcion" rows="10" maxlength="500" style="background-color: #faf3e0; color: #000;"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="id_valor" class="form-label" style="color: #000;">Valor (CLP)</label>
                            <input type="number" class="form-control" id="id_valor" name="valor" style="background-color: #faf3e0; color: #000;">
                        </div>
                        <div class="mb-3">
                            <label for="id_cantidad" class="form-label" style="color: #000;">Cantidad</label>
                            <input type="number" class="form-control" id="id_cantidad" name="cantidad" style="background-color: #faf3e0; color: #000;">
                        </div>
                        <button type="submit" class="btn btn-success btn-lg">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div>
        <button style="margin-top: 20px; background-color: #f0e6d2; border: none; padding: 10px 20px; border-radius: 5px;">
            <a href="{% url 'servicios:home' %}" style="text-decoration: none; color: black;">Volver a Servicios</a>
        </button>
    </div>
{% endblock contenido %}

project/servicios/templates/servicios/detalleservicio.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
  <h1 style="color: #1a1a1a;">🌸Nuestros Servicios🌸</h1>
  <br> 
{% endblock titulo %}
{% block contenido %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'core/img/servicios1.webp' %}" class="img-fluid rounded" alt="Servicio Imagen">
            </div>
            <div class="col-md-6">
                <div class="card p-4 shadow-sm rounded" style="background-color: #faf3e0;">
                    <ul class="list-unstyled">
                        <li style="color: black;">Nombre: {{ servicio.nombre }}</li>
                        <br>
                        <li style="color: black;">Descripción: {{ servicio.descripcion }}</li>
                        <br>
                        <li style="color: black;">Valor (CLP): {{ servicio.valor }}</li>
                        <br>
                        {% if servicio.cantidad %}
                            <li style="color: black;">Cantidad: {{ servicio.cantidad }}</li>
                        {% endif %}
                    </ul>
                </div>
                <div class="text-center mt-3">
                    <button style="background-color: #f0e6d2; border: none; padding: 10px 20px; border-radius: 5px;">
                        <a href="{% url 'servicios:home' %}" style="text-decoration: none; color: black;">Volver a Servicios</a>
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

project/servicios/templates/servicios/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
  <h1 style="color: #1a1a1a;">🌸Nuestros Servicios🌸</h1>
  <br> 
{% endblock titulo %}
{% block contenido %}
  <div>
    <div id="carouselExampleCaptions" class="carousel slide">
      <div class="carousel-indicators">
        <button type="button"
                data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="0"
                class="active"
                aria-current="true"
                aria-label="Slide 1"></button>
        <button type="button"
                data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="1"
                aria-label="Slide 2"></button>
        <button type="button"
                data-bs-target="#carouselExampleCaptions"
                data-bs-slide-to="2"
                aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'core/img/carrusel1.webp' %}"
               class="d-block w-100"
               alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="text-white fw-bold display-4 mb-4" style="text-shadow: 2px 2px 4px #000;">Dialogo Interior</h5>
            <p class="text-white fw-bold lead" style="text-shadow: 2px 2px 4px #000;">Cambia tus pensamientos, Cambia tu Realidad</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'core/img/carrusel2.webp' %}"
               class="d-block w-100"
               alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="text-white fw-bold display-4 mb-4" style="text-shadow: 2px 2px 4px #000;">Emociones Evitadas</h5>
            <p class="text-white fw-bold lead" style="text-shadow: 2px 2px 4px #000;">Permítete sentir, aceptar y transformar</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'core/img/carrusel3.webp' %}"
               class="d-block w-100"
               alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="text-white fw-bold display-4 mb-4" style="text-shadow: 2px 2px 4px #000;">Transmutar</h5>
            <p class="text-white fw-bold lead" style="text-shadow: 2px 2px 4px #000;">Activa tu transformación interna hacia una vida más plena</p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev"
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next"
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <div class="container mt-4">
    <div class="row">
        {% for servicio in servicios %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <img src="{% static 'core/img/servicios1.webp' %}" class="card-img-top" alt="Imagen del servicio">
                <div class="card-body">
                    <h5 class="card-title text-center" style="color: black;">{{ servicio.nombre }}</h5>
                    <div class="text-center mt-3">
                        <a href="{% url 'servicios:servicios_detalle' servicio.id %}" class="btn btn-primary me-2" style="background-color: #8e44ad; border-color: #8e44ad; color: #fff;">
                            Más información aquí
                        </a>
                        <a href="{% url 'servicios:servicios_actualizar' servicio.id %}" class="btn btn-warning" style="background-color: #9b59b6; border-color: #9b59b6; color: #fff;">
                            Actualizar servicio
                        </a>
                        <a href="{% url 'servicios:servicios_borrar' servicio.id %}" class="btn btn-warning" style="background-color: #9b59b6; border-color: #9b59b6; color: #fff;">
                          Dar de baja
                      </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="fs-4 py-4">
      <a href="{% url 'servicios:servicios_crear' %}" class="btn btn-success">Crear un nuevo servicio para la Comunidad</a>
    </div>
    <div>
      <button style="margin-top: 10px; background-color: #f0e6d2; border: none; padding: 10px 20px; border-radius: 5px;">
          <a href="{% url 'core:home' %}" style="text-decoration: none; color: black;">Volver a Home</a>
      </button>
    </div>
</div>

{% endblock contenido %}